services:

  compras:
    build:
      context: ./compras
      dockerfile: Dockerfile
    container_name: compras
    working_dir: /home/compras
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./compras:/home/compras
    command: sh
    ports:
      - "3000:3000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    working_dir: /home/web
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./web:/home/web
    command: sh
    ports:
      - "8080:3000"
    depends_on:
      - compras
