@startuml disgrama-actividades-livre-markket
|Web|
|#AntiqueWhite|Compras|
|Web|
start
:Seleccionar Producto;
|Compras|
fork
:Nuevo pedido;
:Solicitar Forma de Entrega;
|Web|
:Seleccionar Forma de Entrega;
|Compras|
:Forma de Entrega Seleccionada;
if (Despacho?) then (Envío Currier)
:Calcular Envío;
else (retira)
endif
|Compras|
:Solicitar Medio de Pago;
|Web|
:Seleccionar Forma de Pago;
|Compras|
:Forma de Pago Seleccionada;
fork again
:Reservar Producto;
fork again
:Detectar Infracciones;
|Compras|
end fork
if (Existe Infracción) then (si)
:Cancelar Pedido;
fork
|Web|
:Cancelar Pedido e Informar Infracción;
|Compras|
fork again
:Cancelar Reserva producto;
end fork
|Compras|
else (no)
endif
:Confirmar Compra;
:Autorizar Pago;
|Compras|
if (Pago) then (rechazado)
:Cancelar Compra;
fork
|Web|
:Compra Cancelada por problemas de pagos;
|Compras|
fork again
:Cancelar Reserva producto;
|Compras|
end fork
else (autorizado)
endif
:Enviar Producto;
fork
|Web|
:Compra confirmada y en proceso de envío;
|Compras|
fork again
:Enviar producto;
end fork
end 
@enduml