# Arquitectura de Redes y Servicios
# FI-UNPSJB-PM
#
# Imagen para el desarrollo del servidor de node de compras
# Destinada para utilizar en el desarrollo del trabajo de laboratorio.
FROM node:alpine

# Establece el directorio de trabajo
WORKDIR /home/compras

# Establece la variable de entorno para definir el prompt de la terminal
ENV PS1="[compras:\W]\$ "

# Por defecto ejecuta el comando bash
CMD [ "bash" ]